# -*- coding: utf-8 -*-
"""Internship Practicals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13g-uyVSn47gyvURTGh_8ipdCs9W0Aagc
"""

# Project 1: Linear Regression Model (Prediction)



import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# 1. Generate Synthetic Data (Years of Experience vs Salary)
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)  # Linear relationship with noise

# 2. Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and Train the Model
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Make Predictions
y_pred = model.predict(X_test)

# 5. Plot the Results
plt.scatter(X, y, color='blue', label='Data Points')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression Line')
plt.title('Linear Regression Model Prediction')
plt.xlabel('Independent Variable (X)')
plt.ylabel('Dependent Variable (Y)')
plt.legend()
plt.show()

# Print Model Metrics
print(print("=== Project 1 Results ==="))
print(print(f"Intercept: {model.intercept_[0]:.4f}"))
print(print(f"Coefficient (Slope): {model.coef_[0][0]:.4f}"))

# Project 2: Rule-Based Chatbot

import time

def rule_based_chatbot():
    # Define a simple dictionary of rules (lowercase keys for easier matching)
    responses = {
        "hello": "Hello! Welcome to CODTECH IT Solutions. How can I assist you today?",
        "hi": "Hi there! What can I do for you?",
        "who are you": "I am a Rule-Based AI Chatbot developed by Shruti Deshmukh.",
        "internship": "The Artificial Intelligence internship duration is typically 1 to 4 months.",
        "bye": "Goodbye! Have a great day ahead!",
    }

    print("=== Project 2: Rule-Based Chatbot ===")
    print("Type 'bye' to exit the chat.\n")

    while True:
        user_input = input("You: ").strip().lower()

        if user_input == 'bye':
            print(f"Bot: {responses['bye']}")
            break

        # Find match using simple dictionary lookup
        matched_response = responses.get(user_input, "I am sorry, I am programmed with limited rules and didn't quite understand that. Could you ask something else?")

        time.sleep(0.4) # Simulating slight processing latency
        print(f"Bot: {matched_response}\n")

if __name__ == "__main__":
    rule_based_chatbot()

# Project 4: Neural Style Transfer (NST)

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

def generate_ai_text(prompt_text, max_output_length=50):
    print("=== Project 5: Generative Text Model (GPT-2) ===")
    print("Loading pre-trained model weights from HuggingFace...")

    # Load Pre-trained GPT2 tokenizer and model
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    model = GPT2LMHeadModel.from_pretrained("gpt2")

    # Encode context input string to matrix tensor tokens
    input_ids = tokenizer.encode(prompt_text, return_tensors="pt")

    # Generate sequence text token arrays matching weights parameters
    print("Generating response text...")
    output_sequences = model.generate(
        input_ids=input_ids,
        max_length=max_output_length,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        do_sample=True,      # Uses sampling instead of greedy decoding for varied creative output
        top_k=50,            # Limits sample pool to top 50 choices
        top_p=0.95,          # Nucleus sampling filter criteria threshold value
        temperature=0.8     # Controlling creative variance randomness scale value
    )

    # Decode target vector array array back into readable strings
    generated_text = tokenizer.decode(output_sequences[0], clean_up_tokenization_spaces=True)
    return generated_text

if __name__ == "__main__":
    prompt = "The future of Artificial Intelligence in modern software industry is"
    result = generate_ai_text(prompt, max_output_length=60)
    print("\n--- Output Generated Result ---")
    print(result)

import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

def generate_ai_text(prompt_text, max_output_length=60):
    print("=== Project 5: Generative Text Model (GPT-2) ===")

    # 1. Load Pre-trained GPT-2 Model and Tokenizer
    print("Loading pre-trained GPT-2 model weights from Hugging Face...")
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    model = GPT2LMHeadModel.from_pretrained("gpt2")

    # Set the model to evaluation mode (turns off dropout layers)
    model.eval()

    # 2. Tokenize Input Text (Convert string words into numeric Tensor IDs)
    input_ids = tokenizer.encode(prompt_text, return_tensors="pt")

    # 3. Generate Text Sequences using Advanced Decoding Parameters
    print("Generating response text...")
    with torch.no_grad(): # Disable gradient calculation for faster CPU/GPU inference
        output_sequences = model.generate(
            input_ids=input_ids,
            max_length=max_output_length,
            num_return_sequences=1,
            no_repeat_ngram_size=2,   # Prevents the model from repeating phrases
            do_sample=True,           # Enables probabilistic sampling for creative text
            top_k=50,                 # Keeps only the top 50 highest probability tokens
            top_p=0.92,               # Nucleus sampling: cumulative probability threshold
            temperature=0.85,         # Controls randomness (higher = more creative/random)
            pad_token_id=tokenizer.eos_token_id
        )

    # 4. Decode Token IDs back into human-readable text strings
    generated_text = tokenizer.decode(output_sequences[0], clean_up_tokenization_spaces=True)
    return generated_text

if __name__ == "__main__":
    # Define a custom engineering/AI prompt
    input_prompt = "The integration of Artificial Intelligence and Machine Learning in modern industries has"

    # Run generation
    final_output = generate_ai_text(input_prompt, max_output_length=75)

    print("\n" + "="*30)
    print("PROMPT:")
    print(input_prompt)
    print("="*30)
    print("GENERATED OUTPUT:")
    print(final_output)
    print("="*30)